# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='This is name', max_length=255, verbose_name='Student Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Student Surname')),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('phone', models.CharField(help_text='Write your phone number here', max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('skype', models.CharField(max_length=50, null=True, unique=True)),
                ('courses', models.ManyToManyField(to='courses.Courses')),
            ],
        ),
    ]
