# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.CharField(help_text='This is lesson name', max_length=255, verbose_name='Lesson Name'),
        ),
    ]
