# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_auto_20180202_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructors',
            name='cource',
        ),
        migrations.AddField(
            model_name='instructors',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructors',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='name',
            field=models.CharField(help_text='This is name', max_length=255, verbose_name='Instructor Name'),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='surname',
            field=models.CharField(max_length=255),
        ),
    ]
