# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0003_auto_20180203_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructors',
            name='course',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instructors',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
