# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0004_auto_20180203_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='instructors',
            name='course',
        ),
        migrations.AddField(
            model_name='instructors',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instructors.Position'),
        ),
        migrations.AddField(
            model_name='instructors',
            name='course',
            field=models.ManyToManyField(to='instructors.Course'),
        ),
    ]
